### ISSUE TITLE
Liste chanson

### ISSUE THREAD

**Issue by szewenicolas** [clementf/vibz#10]
Lorsque l'on veut ajouter une musique, la possibilité de voter est proposer : A dégager. 

Si on reste appuyer ca fait des trucs louches aussi, genre on peut plus rien faire sur les autres musiques et celle sur laquelle on est rester appuyer apparait en blanc voir meme disparait  :  A changer. 

Dans la playlist, pour activer les options faudrait ajouter un clic comme pour ajouter une musique.

**Comment by hugobisson** [comment]
Réglé dans le push du 02/11
