### ISSUE TITLE
Rotation écran

### ISSUE THREAD

**Issue by szewenicolas** [clementf/vibz#3]
A faire car ne marche pas

**Comment by szewenicolas** [comment]
La rotation fait tous buggé! Je la desactive pour le moment et pour la version alpha.

**Comment by szewenicolas** [comment]
Rotation activée pour toute les activités sauf le menu principal.

**Comment by hugobisson** [comment]
Rotation désactivée pour toutes les activités sauf le main : Permet de simplifier les question de changement et d'adaptation du design en paysage. :+1:
